### ISSUE TITLE
Add support for Facetype.js typeface.js generator for Three.js

### ISSUE THREAD

**Issue by wxyer** [wieslawsoltes/TypefaceUtil#1]
i want to using with threejs,when the whole fonts is too large ,i just convert some charactor,just like facetypejs

**Comment by wieslawsoltes** [comment]
@wxyer Can you provide links to json format and some examples ?

**Comment by wieslawsoltes** [comment]
The output is simple svg path data https://www.w3.org/TR/SVG11/paths.html#PathDataGeneralInformation

Add new exporters is easy when they support svg path data:

https://github.com/wieslawsoltes/TypefaceUtil/blob/4da6542100a45792beb0bd4eb1c88cb83694a566/src/TypefaceUtil/Exporters/CharacterMapSvgExporter.cs#L45

**Comment by wieslawsoltes** [comment]
@wxyer 
https://gero3.github.io/facetype.js/
https://github.com/gero3/facetype.js

**Comment by wxyer** [comment]
thanks a lot ,
